# Generated by Django 5.1.6 on 2025-02-10 03:28

import localflavor.in_.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='state',
            field=localflavor.in_.models.INStateField(default='KA', max_length=2),
        ),
    ]
