# Generated by Django 5.1.6 on 2025-02-10 03:46

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='zip_code',
            field=models.CharField(default='000000', max_length=6, validators=[users.models.validate_in_zip_code]),
        ),
    ]
