# Generated by Django 5.1.6 on 2025-02-12 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('users', '0006_alter_profile_location_alter_profile_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='List',
            new_name='Listing',
        ),
    ]
