# Generated by Django 5.1.6 on 2025-02-12 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_listing_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='brand',
            field=models.CharField(choices=[('kia', 'Kia'), ('renault', 'Renault'), ('maruti suzuki', 'Maruti Suzuki'), ('tata', 'Tata'), ('ford', 'Ford'), ('volkswagon', 'Volkswagon'), ('hyundai', 'Hyundai'), ('mahindra', 'Mahindra'), ('nissan', 'Nissan'), ('mg', 'MG'), ('skoda', 'Skoda'), ('bmw', 'BMW'), ('mercedes benz', 'Mercedes Benz'), ('audi', 'Audi'), ('subaru', 'Subaru'), ('tesla', 'Tesla'), ('jaguar', 'Jaguar'), ('land rover', 'Land Rover'), ('bentley', 'Bentley'), ('bugatti', 'Bugatti'), ('ferrari', 'Ferrari'), ('lamborghini', 'Lamborghini'), ('honda', 'Honda'), ('toyota', 'Toyota'), ('chevrolet', 'Chevrolet'), ('porsche', 'Porsche')], default=None, max_length=24),
        ),
    ]
